import logo from "./extensions/logo.png";
import favicon from "./extensions/favicon.png";

const customColors = {
  primary100: "#f6f9fd",
  primary200: "#e1e9f9",
  primary300: "#b7c9f1",
  primary400: "#8ca9e8",
  primary500: "#6189E0",
  primary600: "#3a7dd4",
  primary700: "#2764b4",
  primary800: "#1e4d8a",
  primary900: "#153660",
  primary1000: "#0c1e36",
  buttonPrimary500: "#6189E0",
  buttonPrimary600: "#3a7dd4",
}

export default {
  config: {
    tutorials: false,
    auth: {
      logo: logo
    },
    menu: {
      logo: logo
    },
    head: {
      favicon: favicon
    },
    locales: [
      "fr",
    ],
    theme:{
      light: {
        colors: customColors,
      },
      dark: {
        colors: customColors,
      },
    },
    translations: {
      fr: {
        "Auth.form.active.label": "Active",
        "Auth.form.button.forgot-password": "Envoyer email",
        "Auth.form.button.go-home": "RETOURNER À L'ACCUEIL",
        "Auth.form.button.login": "Login",
        "Auth.form.button.login.providers.error": "Nous ne pouvons pas vous connect en utilisant le fournisseur sélectionné.",
        "Auth.form.button.login.strapi": "Se connecter en utilisant Strapi",
        "Auth.form.button.password-recovery": "Récuperation de mot de passe",
        "Auth.form.button.register": "On commence!",
        "Auth.form.confirmPassword.label": "Confirmer mot de passe",
        "Auth.form.currentPassword.label": "Mot de passe actuel",
        "Auth.form.email.label": "Email",
        "Auth.form.email.placeholder": "e.x. kai@doe.com",
        "Auth.form.error.blocked": "Votre compte a été banni pas un administrateur.",
        "Auth.form.error.code.provide": "Code fourni incorrecte.",
        "Auth.form.error.confirmed": "Votre compte email n'est pas confirmé.",
        "Auth.form.error.email.invalid": "Cet adresse mail n'est pas valide.",
        "Auth.form.error.email.provide": "Entrer votre nom d'utilisateur ou votre email.",
        "Auth.form.error.email.taken": "Email déjà utilisé.",
        "Auth.form.error.invalid": "Identificateur ou mot de passe invalide.",
        "Auth.form.error.params.provide": "Paramètres fournis incorrectes.",
        "Auth.form.error.password.format": "Votre mot de passe ne peut pas contenir la symbole `$` plus de trois fois.",
        "Auth.form.error.password.local": "Cet utilisateur n'a jamais fourni un mod de passe locale, entrez en utilisant le fournisseur entré au moment de la creation de la compte",
        "Auth.form.error.password.matching": "Les mot de passe ne sont pas égaux.",
        "Auth.form.error.password.provide": "Fournissez votre mot de passe.",
        "Auth.form.error.ratelimit": "Trop des essais, essayez plus tard.",
        "Auth.form.error.user.not-exist": "Cet email n'existe pas.",
        "Auth.form.error.username.taken": "Nom d'utilisateur déjà existant.",
        "Auth.form.firstname.label": "Prénom",
        "Auth.form.firstname.placeholder": "e.g. Kai",
        "Auth.form.forgot-password.email.label": "Entrer votre email",
        "Auth.form.forgot-password.email.label.success": "Email envoyé avec success à",
        "Auth.form.lastname.label": "Nom",
        "Auth.form.lastname.placeholder": "e.g. Doe",
        "Auth.form.password.hide-password": "Cacher mot de passe",
        "Auth.form.password.hint": "Doit être au moins 8 caractéres, 1 mayuscule, 1 minuscule et 1 nombre",
        "Auth.form.password.show-password": "Montrer mot de passe",
        "Auth.form.register.news.label": "Me mantenir au jour avec les nouvelles fonctionnalités et améliorations futures (En faisant cela vous acceptez les {terms} et la {policy}).",
        "Auth.form.register.subtitle": "Les credentiels sont seulement utilisés dans Strapi. Tout les données seront stockés dans votre base de données.",
        "Auth.form.rememberMe.label": "Se souvenir de moi",
        "Auth.form.username.label": "Nom d'utilisateur",
        "Auth.form.username.placeholder": "e.g. Kai_Doe",
        "Auth.form.welcome.subtitle": "Entrer dans votre compte",
        "Auth.form.welcome.title": "Bienvenue à votre gesteur de contenu!",
        "Auth.link.forgot-password": "Mot de passe oublie?",
        "Auth.link.ready": "Prêt à renter?",
        "Auth.link.signin": "Entrer",
        "Auth.link.signin.account": "Déjà un compte?",
        "Auth.login.sso.divider": "Ou entrer avec...",
        "Auth.login.sso.loading": "Chargement des fournisseurs...",
        "Auth.login.sso.subtitle": "Entrer à votre compte via SSO",
        "Auth.privacy-policy-agreement.policy": "politique de privacité",
        "Auth.privacy-policy-agreement.terms": "termes",
        "Auth.reset-password.title": "Réinitialiser mot de passe",
        "app.components.LeftMenu.navbrand.title": "Gestion de contenu",
        "app.components.LeftMenu.navbrand.workplace": "H2VL",
        "content-type-builder.form.attribute.item.privateField.description": "Cet champ ne se montrera pas dans la réponse de l'API",
        "content-type-builder.form.attribute.media.allowed-types": "Sélectionner les types de média autorisés",
        "content-type-builder.form.attribute.media.allowed-types.option-files": "Fichiers",
        "content-type-builder.form.attribute.media.allowed-types.option-images": "Images",
        "content-type-builder.form.attribute.media.allowed-types.option-videos": "Videos",
        "content-type-builder.form.attribute.media.option.multiple": "Média multiple",
        "content-type-builder.form.attribute.media.option.multiple.description": "Meilleur pour sliders, carousels et téléchargement des fichiers multiples",
        "content-type-builder.form.attribute.media.option.single": "Média unique",
        "content-type-builder.form.attribute.media.option.single.description": "Meilleur pour avatars, images profile ou images de couverture",
        "content-type-builder.form.attribute.text.option.long-text": "Texte longue",
        "content-type-builder.form.attribute.text.option.long-text.description": "Meilleur pour descriptions, biographies. La recherche exacte est désactivé.",
        "content-type-builder.form.attribute.text.option.short-text": "Texte Court",
        "content-type-builder.form.attribute.text.option.short-text.description": "Meilleur pour titres, noms, liens (URL). Active aussi la recherche exacte pour le champ.",
        "content-type-builder.attribute.boolean": "Booléen",
        "content-type-builder.attribute.boolean.description": "Oui ou non, 1 or 0, vrai ou faux",
        "content-type-builder.attribute.component": "Composant",
        "content-type-builder.attribute.component.description": "Groupe de champs que vous pouvez répeter ou réutiliser",
        "content-type-builder.attribute.customField": "Champ personnalisé",
        "content-type-builder.attribute.date": "Date",
        "content-type-builder.attribute.date.description": "Un Sélecteur des dates avec des heures, minutes et secondes",
        "content-type-builder.attribute.datetime": "Datetime",
        "content-type-builder.attribute.dynamiczone": "Zone dynamique",
        "content-type-builder.attribute.dynamiczone.description": "Sélectionner le composant dynamique au moment d'editer le contenu",
        "content-type-builder.attribute.email": "Email",
        "content-type-builder.attribute.email.description": "Champ email avec validations de format",
        "content-type-builder.attribute.enumeration": "Énumération",
        "content-type-builder.attribute.enumeration.description": "Liste de valeurs, après sélectionner une",
        "content-type-builder.attribute.json": "JSON",
        "content-type-builder.attribute.json.description": "Data en format JSON",
        "content-type-builder.attribute.media": "Média",
        "content-type-builder.attribute.media.description": "Fichiers comme images, videos, etc",
        "content-type-builder.attribute.null": " ",
        "content-type-builder.attribute.number": "Nombre",
        "content-type-builder.attribute.number.description": "Nombres (entier, flottant, decimal)",
        "content-type-builder.attribute.password": "Mot de passe",
        "content-type-builder.attribute.password.description": "Champ mot de passe avec chiffrage",
        "content-type-builder.attribute.relation": "Relation",
        "content-type-builder.attribute.relation.description": "Fait référence à un type de collection",
        "content-type-builder.attribute.richtext": "Texte Enrichi (Markdown)",
        "content-type-builder.attribute.richtext.description": "L'editeur de texte enrichi clasique",
        "content-type-builder.attribute.blocks": "Texte Enrichi (Bloque)",
        "content-type-builder.attribute.blocks.description": "Le nouveau editeur de texte enrichi base sur JSON",
        "content-type-builder.attribute.text": "Texte",
        "content-type-builder.attribute.text.description": "Texte petit ou longue pour un titre ou description",
        "content-type-builder.attribute.time": "Temps",
        "content-type-builder.attribute.timestamp": "Etiquette de temps",
        "content-type-builder.attribute.uid": "UID",
        "content-type-builder.attribute.uid.description": "Identificateur unique",
        "content-type-builder.listView.headerLayout.description": "Construire l'arquitecture de données de votre contenu",
        "content-type-builder.menu.section.components.name": "Composants",
        "content-type-builder.menu.section.models.name": "Types de collection",
        "content-type-builder.menu.section.single-types.name": "Types uniques",
        "content-type-builder.button.attributes.add.another": "Ajouter autre champ",
        "content-type-builder.button.component.add": "Ajouter un composant",
        "content-type-builder.button.component.create": "Créer nouveau composant",
        "content-type-builder.button.model.create": "Créer nouveau type de collection",
        "content-type-builder.button.single-types.create": "Créer nouveau type unique",
        "content-type-builder.modalForm.attribute.form.base.name.description": "Espace interdit dans le nom de l'attribut",
        "content-type-builder.modalForm.attribute.form.base.name.placeholder": "e.x. slug, seoUrl, canonicalUrl",
        "content-type-builder.modalForm.attribute.target-field": "Champ Attaché",
        "content-type-builder.modalForm.attributes.select-component": "Selectionner un composant",
        "content-type-builder.modalForm.attributes.select-components": "Selectionner le composant",
        "content-type-builder.modalForm.collectionType.header-create": "Créer un type de collection",
        "content-type-builder.modalForm.component.header-create": "Créer un composant",
        "content-type-builder.modalForm.components.create-component.category.label": "Selectionner une catégorie ou entrer un nom pour créer une nouvelle",
        "content-type-builder.modalForm.components.icon.label": "Icone",
        "content-type-builder.modalForm.empty.button": "Ajouter champs personalisés",
        "content-type-builder.modalForm.empty.heading": "Rien ici pour le moment.",
        "content-type-builder.modalForm.empty.sub-heading": "Trouvez ce que vous cherchez dans une longue gamme des extensions.",
        "content-type-builder.modalForm.editCategory.base.name.description": "Espace interdit dans le nom de la catégorie",
        "content-type-builder.modalForm.header-edit": "Editer {name}",
        "content-type-builder.modalForm.header.categories": "Categories",
        "content-type-builder.modalForm.header.back": "Retourner",
        "content-type-builder.modalForm.singleType.header-create": "Créer un type unique",
        "content-type-builder.modalForm.sub-header.addComponentToDynamicZone": "Ajouter le nouveau composant à la zone dynamique",
        "content-type-builder.modalForm.sub-header.attribute.create": "Ajouter nouveau champ {type}",
        "content-type-builder.modalForm.sub-header.attribute.create.step": "Ajouter nouveau composant ({step}/2)",
        "content-type-builder.modalForm.sub-header.attribute.edit": "Editer {name}",
        "content-type-builder.modalForm.sub-header.chooseAttribute.collectionType": "Sélectionner un champ pour votre nouveau type de collection",
        "content-type-builder.modalForm.sub-header.chooseAttribute.component": "Sélectionner un champ pour votre composant",
        "content-type-builder.modalForm.sub-header.chooseAttribute.singleType": "Sélectionner un champ pour votre type unique",
        "content-type-builder.modalForm.custom-fields.advanced.settings.extended": "Réglages étendus",
        "content-type-builder.modalForm.tabs.custom": "Personalisé",
        "content-type-builder.modalForm.tabs.custom.howToLink": "Comment ajouter champs personnalisés",
        "content-type-builder.modalForm.tabs.default": "Par défaut",
        "content-type-builder.modalForm.tabs.label": "Onglets types par défaut et personnalisés",
        "content-type-builder.modelPage.attribute.relation-polymorphic": "Relation (polymorphique)",
        "content-type-builder.modelPage.attribute.relationWith": "Relation avec",
        "content-type-builder.plugin.name": "Constructeur de type de contenu"
      }
    }
  },
  bootstrap(app: any) {
    console.log(app);
  },
};
