services:
  strapi:
    build: ./cms
    env_file: ./cms/.env
    environment:
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
    healthcheck:
      start_period: 60s
      timeout: 3s
      interval: 15s
      test: "curl -f http://localhost:1337 || exit 1"
    volumes:
      - ./cms/.tmp:/srv/app/.tmp
    ports:
      - "1337:1337"

  astro:
    build: ./client
    env_file: ./client/.env
    ports:
      - "4321:4321"
    healthcheck:
      start_period: 60s
      timeout: 3s
      interval: 15s
      test: "curl -f http://localhost:4321 || exit 1"
    depends_on:
      strapi:
        condition: service_healthy
