services:
  strapi:
    build: ./cms
    environment:
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
      - NODE_ENV=production
    volumes:
      - ./cms/.tmp:/srv/app/.tmp
    ports:
      - "1337:1337"

  astro:
    build: ./client
    environment:
      - NODE_ENV=production
    ports:
      - "4321:4321"
    depends_on:
      - strapi
