name: Client page build with checkout
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/heyner/H2VL
    steps:
      - name: Pull repository
        run: git pull origin main
      - name: Install dependencies
        run: npm ci
      - name: Set node into production mode
        run: export NODE_ENV="production"
      - name: Build cms
        run: npm run build -w=cms
      - name: Build client
        run: npm run build  -w=client
      - name: Restart pm2
        run: pm2 restart ecosystem.config.js
