name: Client page build with checkout
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/heyner/H2VL
    steps:
      - name: Pull repository
        run: git pull origin main
      - name: Install dependencies
        run: npm ci
      - name: Build cms
        run: rm -rf ./cms/dist && npm run build -w=cms
      - name: Restart cms
        run: pm2 restart ecosystem.config.js --only cms
      - name: Build client
        run: rm -rf ./client/dist && npm run build -w=client
      - name: Restart client
        run: pm2 restart ecosystem.config.js --only client
