name: Client page build with checkout
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/heyner/H2VL
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build cms
        run: npm run build -w=cms
      - name: Build client
        run: npm run build  -w=client
      - name: Restart pm2
        run: pm2 restart ecosystem.config.js
