name: NPM Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * */1"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Build client
        run: cd ~/H2VL && npm run build  -w=client
