name: Client page build without checkout
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/heyner/H2VL
    steps:
      - name: Build client
        run: npm run build  -w=client
